"""Initial Migration

Revision ID: 07edd7415809
Revises: 
Create Date: 2022-05-09 15:18:43.922642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07edd7415809'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
