"""delete categories

Revision ID: 470c05f9dc5e
Revises: 9537bfa6b6a4
Create Date: 2022-05-11 02:15:35.583410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '470c05f9dc5e'
down_revision = '9537bfa6b6a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    op.drop_constraint('comments_category_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'category_id')
    op.add_column('pitches', sa.Column('category', sa.Text(), nullable=False))
    op.alter_column('pitches', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('pitches', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('pitches', 'posted',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint('pitches_category_id_fkey', 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'downvotes')
    op.drop_column('pitches', 'urlToImage')
    op.drop_column('pitches', 'category_id')
    op.drop_column('pitches', 'upvotes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('upvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('urlToImage', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('downvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pitches_category_id_fkey', 'pitches', 'categories', ['category_id'], ['id'])
    op.alter_column('pitches', 'posted',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('pitches', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('pitches', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('pitches', 'category')
    op.add_column('comments', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_category_id_fkey', 'comments', 'categories', ['category_id'], ['id'])
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='categories_pkey')
    )
    # ### end Alembic commands ###
