"""add description, url to image columns

Revision ID: a400335403ce
Revises: 98b134cec310
Create Date: 2022-05-10 17:57:27.548325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a400335403ce'
down_revision = '98b134cec310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('pitches', sa.Column('urlToImage', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'urlToImage')
    op.drop_column('pitches', 'description')
    # ### end Alembic commands ###
